package com.Exception;

public class Arithmetic_ {
    public static void main(String[] args)  throws Exception{

        int n1 = 10;
        int n2 = 0;
//        try {
            int res = n1 / n2;
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

        System.out.println("++++ ");

        /*
        程序抛出异常  ArithmeticException

         */

    }
}
